pouriyajamshidi/tcping

tcping.go
Related to #10 
* Just changed the hasResults condition.
Slowest, fastest and average are displayed as 0ms.
That means those values are less than 1 ms.
=> Fix statistics display on rtt is less than 1 ms

README.md, go.mod, go.sum, tcping.go, tcping_test.go
Related to #4 
(only replace with flag package)
* Add tests.
* Add usage option to READ.ME.
**PermuteArgs** can be confusing.
Flag parsing stops just before the first non-flag argument in [flag package](https://pkg.go.dev/flag#:~:text=Flag%20parsing%20stops%20just%20before%20the%20first%20non%2Dflag%20argument%20(%22%2D%22%20is%20a%20non%2Dflag%20argument)%20or%20after%20the%20terminator%20%22%2D%2D%22.).
So, **permuteArgs** keeps the sequence uniform.
ex)
`tcping 127.0.0.1 -p 8080`
↓
`tcping -p 8080 127.0.0.1`
Please review, before I add flag to retry resolving target's hostname.
=> Add -r option to retry resolving target's hostname

tcping.go, tcping_test.go
Related to #15 
There are a few things to check.
* I have added error cases (errArgsFlagHasNoValue, errArgsNotEnough) for testing purposes, but is it subtle to define errors that are not actually used?
* I included **checkLatestVersion()** in **processUserInput(tcpStats *stats)**.
This is because if there is some other error after parse, the user will not get to the update display.
But it seems a bit odd in logic.
Please review.
=> Provide a flag to check for newer versions

statsprinter.go, tcping.go
implement sub-millisecond timing report.
- Convert `rtt`'s `uint` slice to `float32`
- Change print statements to display timings with 3 decimal places
- Report min/max rtt using floating points similar to avg
Closes #54
=> implement sub-milliseocnd timing report

CHANGELOG.md, tcping.go
- Close TCP connections faster by removing the `defer` keyword
=> close TCP connections faster

tcping.go, tcping_test.go
Removed magic `1e6`, replaced it by `time.Millisecond`, which is a lot readable.
At first, I wanted to remove that function and just replace it with `duration.Milliseconds()`, but that (for some reason) drops decimal points (returns int64, not float64 like `.Seconds()` or `.Hours()`). So, I also added a comment explaining why that function should be used.
=> refactor: nanoToMillisecond function

README.md, tcping.go
Add `-c` flag
Edge cases:
1. `-c` is uint, any negative number will fallback to `usage()`
2. `-c 0` = default behaviour, no limits
3. `-r 2 -c 3` will quit after exactly 3 probes (probe -> probe -> resolve -> probe -> quit) 
Closes #72 
=> feat: add `c` flag

statsprinter.go, tcping.go
tcping now keeps tracks of successful(!) hostname changes, and reports them in json/plane printers in statistics screen
<details><summary>Example output of multiple unsuccessful resolves and some successful ones</summary>
This uses old output format, there are screenshots of the new format below
<pre>
> go run . fb.com 443 -r 2
TCPinging fb.com on port 443
No reply from fb.com (2a03:2880:f103:83:face:b00c:0:25de) on port 443 TCP_conn=1
No reply from fb.com (2a03:2880:f103:83:face:b00c:0:25de) on port 443 TCP_conn=2
retrying to resolve fb.com
No reply from fb.com (2a03:2880:f162:81:face:b00c:0:25de) on port 443 TCP_conn=1
No reply from fb.com (2a03:2880:f162:81:face:b00c:0:25de) on port 443 TCP_conn=2
retrying to resolve fb.com
No response received for 4 seconds
Reply from fb.com …
=> feat: report hostname changes

statsprinter_test.go, tcping_test.go
This is mostly a POC PR for improving tests and code coverage.
This PR adds:
- Test server for making probes
- Test printer that simply implements `printer` interface but does nothing. Printers could\should be tester separately.
- Example tests for `handleConnSuccess`/`handleConnError`
More tests could be added later as a part of other PRs
=> tests: add basic test server and probe success/fail tests

tcping.go
In PR https://github.com/pouriyajamshidi/tcping/commit/11b5aedcd340470a81b46a743df94a055c1d0e5c the `stdin` logic was refactored and this caused tcping to ignore Windows' `printStatistics` request.
This patch fixes it.
=> fix Windows Enter key detection

.github/workflows/container-publish.yml
This pr fixes the `GitHub Actions: Deprecating save-state and set-output commands`
changes these lines
https://github.com/pouriyajamshidi/tcping/blob/5ec50b47c4cca6a770523933d3c4d99910e81191/.github/workflows/container-publish.yml#L40C1-L42C74
https://github.com/pouriyajamshidi/tcping/issues/98
Closes #98 
=> fixed CI warnings #98

Makefile
remove size instruction from Makefile for `.deb` pakcage
=> remove size instruction

db.go, db_test.go
Fix db rtt floating point number to .3f
Closes https://github.com/pouriyajamshidi/tcping/issues/146
=> reduce RTT floating point precision when storing to db

Makefile
Changes to Makefile
Added support for Linux arm 64 following the structure of the code in the Makefile. Tested that the executable is generated properly and does not break any of the existing code.
#45
- [yes] I have performed a self-review of my code
- [yes] I have run `make check` and there are no failures.
=> Added support for linux arm64 in makefile

CHANGELOG.md
- new feature: add `-show-failures-only` flag to omit printing successful probes
- new feature: re-add **static** Linux binary. Thanks to @daniql
- new feature: add support for Linux `arm64` in Makefile. Thanks to @ChrisClarke246
- fix: extra precision for seconds calculation when the value is under a second. Thanks to @daniql
- refactor: migrate to a pure-Go `sqlite` package. Thanks to @wizsk
- refactor: user flag handlers
- cleanup: user input functions. Thanks to @friday963
- chore: fix typos
=> release version 2.5.0

Makefile
- Split the 'build' section into smaller targets. The new targets: 'create_dirs', 'build_linux_amd64', 'build_linux_static', 'build_linux_arm', 'build_windows', 'build_macos', 'build_macos_arm','build_freebsd'.
- Updated .PHONY list
- Resolves #185
=> Refactor Makefile: Split build section into smaller, distinct targets

.gitignore, Makefile, README.md, tcping.go
Rewrite Makefile to rely less on `.PHONY` targets.
While working on the logic problem in #242, I found the current Makefile setup to be quite clumsy. No offence to the previous author, but it seems to me that it's quite hastily cobbled together. Lots of unnecessary code duplication and under-utilisation of the strengths of make (specifically, its focus on file generation).
So I decided to overhaul the whole thing. A bit drastic, but I believe it's for a good cause.
Closes #242.
=> Rewrite Makefile

.dockerignore, .github/workflows/container-publish.yml, Dockerfile, Makefile
Containerise the build process. Motivation detailed [here](https://github.com/pouriyajamshidi/tcping/pull/245#discussion_r1791118412), posted here verbatim:
> Currently, the build process itself is not performed in a containerised environment, which goes against the key spirits of containerisation - platform-independence and reproducibility. In short, the build process in its current state is dependent on a working toolchain on the host, which alongside its other environmental factors is largely opaque to the end user (or even to the packager themselves). Setting up the build environment in a containerised environment improves the observability, reliability, and trustworthiness of the build artefact(s).
>
> As of how a multi-stage Dockerfile fits into this equation, this is just so that …
=> Containerise build process

README.cn.md, README.md
Fixes `go install` documentation, as discussed in #262 
I updated the command for the chinese README as well, but was unable to add the sentence mentioning the minimum version.
If someone wants to provide the translation so I can add it to this PR, feel free to ; otherwise, the error message during `go install` is probably clear enough that it's fine not explicitly documenting the version constraint in the first place.
Closes https://github.com/pouriyajamshidi/tcping/issues/262
Documentation fix.
=> Fix `go install` installation instructions, and mention minimum go version

csv.go
I think latency metric should be an empty string in case of failed probes in the csv printer.
This PR also addresses adding an empty string in case show-local-address option was enabled.
Closes #
=> fix: represent latency as empty string in csv printer failed probes

Makefile
fix Windows builds due to lack of defined OS type
=> fix Windows builds due to lack of defined OS type

CHANGELOG.md
- release: add tcping to [WinGet](https://learn.microsoft.com/en-us/windows/package-manager/winget) [#113](https://github.com/pouriyajamshidi/tcping/issues/113)
- bug: fix name resolution in static builds with `-4` flag causing name resolution failures due to _IPv4-mapped IPv6 addresses_
- CI: apply **Revive** suggestions
- CI: add **Revive** to CI
- CI: add **Revive** config
- documents: revamp and simplify the README file
- documents: update the Chinese translation thanks to @edwinjhlee
=> update for release v2.7.1
