tcping.go

Fixes the longest downtime calculation bug that was resulting in erroneous display of information.
Closes #2

Fix longest downtime calculation bug

---

.gitignore
tcping.go
tcping_test.go

related #8
* Make calcTime possible to convert minutes to hours.
* Add tests.
* Delete calcSeconds.
I felt that it would not look good to handle the time with float64 in this case, so I decided to implement it this way.
If this doesn't match your imagination, I apologize:pray:

Add time conversion

---

tcping.go

Related to #5.
* Crean up longestTime structure.
* Make to show longest uptime.
* Make to update longest downtime even in cases where it is not up afterwards.

Show longest uptime

---

.github/workflows/container-publish.yml

i have made a tiny change, can you try now picking of go version

fix picking of go version

---

.github/workflows/codeql-analysis.yml
.github/workflows/container-publish.yml
.github/workflows/stale.yml

Upgraded the following actions
- actions/stale
- actions/setup-go
- sigstore/cosign-installer
- docker/login-action
- docker/metadata-action
Closes #48

Update actions versions

---

tcping.go

refactor `tcping` function and simplify it to improve readability.

refactor tcping function and simplify it

---

tcping.go

fix undeclared statsPrinter warning

fix undeclared statsPrinter warning

---

README.md

fix readme's contributing section

fix readme's contributing section

---

README.md

fix issues shield of readme

---

Makefile
README.md

add Apple M1 (ARM64) support

---

Makefile
go.mod
go.sum

add statically linked Linux binary
closes #59

add statically linked Linux binary

---

CHANGELOG.md
README.md
tcping.go

adds -4 and -6 flags to enforce IP address version resolution
Closes #64

add -4 and -6 flags to enforce IP address version resolution

---

README.md

Fixes typos and broken links in the README file

fix typos and broken links

---

tcping.go

Fixes a bug that prevented a correct IP version selection when passed `-4` or `-6` flags.

fix IP version enforcement bug

---

CHANGELOG.md
tcping.go

update for release 1.22.1

---

README.md

Updates Windows Terminal link
closes #82

update Windows Terminal link

---

statsprinter.go

fix: packet loss NaN

---

LICENSE

Update LICENSE date

---

statsprinter.go
tcping.go
tcping_test.go

- separate user input into its own struct
- better variable names
- update tests

- separate user input into its own struct

---

tcping.go

memory alignment of structs

---

tcping.go

- rearrange functions for better readability
- rename some variables for better readability

- rearrange functions for better readability

---

Makefile

- Create `.deb` package using Makefile to make tcping `apt installable`.
- Add BSD support
Closes #95

add .deb support to make tcping apt installable

---

tcping.go
tcping_test.go

- rework hostname resolution logic
- replace net.IP with netip.Addr
- update tests
Closes https://github.com/pouriyajamshidi/tcping/issues/40

refactor hostname resolution logic

---

tcping.go

- fix time report bug
- increase DNS resolution timeout
Closes #83

fix time report bug

---

Makefile

update Debian package name

---

tcping.go

##
- fix random IP selector bug
- address rare IPv4 formatting issue when it is IPv6 encapsulated

fix random IP selector bug

---

README.md

improve Debian section

---

.gitignore
db.go
db_test.go
go.mod
go.sum
tcping.go

this pr adds the functionality to save connection details into a `sqlite3` db.
- 2 files added `db.go` and `db_test.go`
- added `-db` flag. 
- important tests are written.
- needs review and feedback
Closes https://github.com/pouriyajamshidi/tcping/issues/46

Add option for saving to db

---

tcping.go
tcping_test.go

Implement custom dial timeout feature
#7
Closes #7

Implement custom timeout value feature

---

db.go
tcping.go

I made a small change to `permuteArgs` to make the -db flag work. The fix is just awful but it works. 
Closes #131
I don't want to steal the job of @wizsk, but I just wanted to show a solution to the issue.

make -db flag work

---

README.md

`--db` flag documentation was missing in README.md. So, I added it.

updated Flag section in readme with `--db`

---

db.go
tcping.go

Database related bug fixes
1. db unexpected closure fixed
2. total duration calculation
3.  write hostname changes at final call to `database.printStatistics`
4. longest uptime/dowtime default duration set to "0s". start and end time to `""`
Closes https://github.com/pouriyajamshidi/tcping/issues/134

Db bug fixes

---

db_test.go

uncomment database tests

---

README.md

add `-t` flag docs

---

.gitignore
tcping.go

Added functionality to select local network interface for pining.
Closes https://github.com/pouriyajamshidi/tcping/issues/123

Add support for selecting network Interface

---

LICENSE

update year in license file

---

README.md

mention false positives by antimalware systems on Windows systems

mention false positives by antimalware systems on Windows systems

---

.github/workflows/container-publish.yml

bump cosign version

---

.github/workflows/container-publish.yml

bump GitHub Actions version

---

Makefile

fixing #161
added back in the static linux binary to makefile that was previously removed
Closes #161 
- [ X] I have performed a self-review of my code
- [X ] If it is a core feature, I have added tests.
- [ X] I have run `make check` and there are no failures.

re-added static linux binary

---

tcping.go

This commit adds a new flag, `show-failures-only` so that users can omit printing success reports and only view the failed ones.

implement display failures only flag

---

README.md

update flag section of README to include show-failures-only

update flag section of README to include show-failures-only

---

README.md
tcping.go

Added "h" flag to show help, which calls usage()
Updated readme to contain the new flag 
Closes #213 
- [ YES ] I have performed a self-review of my code
- [ NO ] If it is a core feature, I have added tests.
- [ NO ] I have run `make check` and there are no failures.
- [ YES ] New feature (non-breaking change which adds functionality)
- [ YES ] This change requires a documentation update

add -h flag to show help #213

---

README.md

Correct Chinese expression in the README page.
中国人 neans 'Chinese people'
中文 means 'Chinese language'
Thank you for this great project and being convenience to Chinese users.

Correct Chinese expression in the README page : 中国人 -> 中文

---

README.cn.md
README.md

Add one more convinient way to use tcping.
Add `x tcping` in README.md and README.cn.md
Related to #243

Add `x tcping` in README.md and README.cn.md

---

LICENSE

reverts license date to what it was before.

revert license date

---

statsprinter.go
statsprinter_test.go
tcping.go

rename planePrinter to colorPrinter to match the actual functionality, paving the way for #253

rename planePrinter to colorPrinter for #253

---

README.md

add --no-color flag to README

---

README.md

update flags for v2.7.0 release

update flags for v2.7.0 release

---

CHANGELOG.md
statsprinter.go
statsprinter_test.go
tcping.go

rename plane to plain printer

---

CHANGELOG.md
csv.go
tcping.go

apply revive's suggestions

---

README.md

revamp and simplify README

---

README.md

fix directives and some links

---

README.md

more fixes to the README

---

README.md

add WinGet instructions and minor readability improvements
closes #113

add WinGet instructions and minor readability improvements

---

CHANGELOG.md

add WinGet

---

Makefile

bump version to 2.7.1
